### ISSUE TITLE
Remove regions plz

### ISSUE THREAD

**Issue by jmeas** [thejameskyle/backbone.baseview#1]
`layoutView.insertChild(selectorString, viewInstance);` is much betta. Adding a new concept to show child views, like "regions," is just adding to the conceptual overhead of using this lib

**Comment by thejameskyle** [comment]
I was just killing them completely locally

**Comment by thejameskyle** [comment]
Done.

**Comment by jmeas** [comment]
hah nice. I'm gonna look into transitioning off of Marionette by using this view instead.

**Comment by thejameskyle** [comment]
I would hold off, there's a bit more I want to do before this is ready. I'm porting some of the things we had to do at CF to be cleaner and open source projects.

**Comment by jmeas** [comment]
Mmk. I don't plan to do it anytime in the foreseeable future, anyways. Just a distant goal the next time I'm refactoring that Marionette app... :P
